"""Pridany telefon a email do Firmy

Revision ID: 4e7ff78c62fd
Revises: 
Create Date: 2026-09-30 12:09:40.643450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7ff78c62fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('telefon')

    # ### end Alembic commands ###
